import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatCurrency } from '../utils/currency';
import { formatDisplayDate } from '../utils/dates';

export const generateDailyPDF = (record, hotelName, isAggregated = false) => {
  if (!record) return;

  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(44, 62, 80);
  doc.text("Daily Report", 14, 22);
  
  doc.setFontSize(12);
  doc.setTextColor(127, 140, 141);
  const title = isAggregated || hotelName === 'ALL' ? 'All Hotels Aggregated' : `Hotel: ${hotelName}`;
  doc.text(title, 14, 30);
  doc.text(`Date: ${formatDisplayDate(record.date)}`, 14, 36);

  // Summary Boxes
  doc.setFillColor(248, 249, 250);
  doc.rect(14, 42, 60, 20, 'F');
  doc.rect(78, 42, 60, 20, 'F');
  doc.rect(142, 42, 54, 20, 'F');

  doc.setFontSize(10);
  doc.text("Total Income:", 18, 50);
  doc.text("Total Expense:", 82, 50);
  doc.text("Net Profit:", 146, 50);

  doc.setFontSize(14);
  doc.setTextColor(46, 204, 113);
  doc.text(formatCurrency(record.income?.total || 0), 18, 58);
  doc.setTextColor(231, 76, 60);
  doc.text(formatCurrency(record.totalExpense || 0), 82, 58);
  
  const netProfit = record.netProfit || 0;
  doc.setTextColor(netProfit >= 0 ? 46 : 231, netProfit >= 0 ? 204 : 76, netProfit >= 0 ? 113 : 60);
  doc.text(`${netProfit >= 0 ? '' : '-'}${formatCurrency(Math.abs(netProfit))}`, 146, 58);

  // Income Breakdown
  doc.setFontSize(12);
  doc.setTextColor(44, 62, 80);
  doc.text("Income Breakdown", 14, 75);
  
  doc.autoTable({
    startY: 80,
    head: [['Type', 'Amount']],
    body: [
      ['Cash', formatCurrency(record.income?.cash || 0)],
      ['Online', formatCurrency(record.income?.online || 0)],
    ],
    theme: 'grid',
    headStyles: { fillColor: [46, 134, 171] },
    margin: { left: 14 }
  });

  // Expense List
  const finalY = doc.lastAutoTable.finalY || 80;
  
  doc.setFontSize(12);
  doc.setTextColor(44, 62, 80);
  doc.text("Expenses", 14, finalY + 15);

  const expensesBody = (record.expenses || []).map(e => {
    const row = [e.category || 'Uncategorized', e.note || '-', formatCurrency(e.amount)];
    if (isAggregated || hotelName === 'ALL') {
      row.unshift(e.hotelSource || 'Unknown');
    }
    return row;
  });

  const expenseHead = isAggregated || hotelName === 'ALL' 
    ? [['Hotel', 'Category', 'Note', 'Amount']]
    : [['Category', 'Note', 'Amount']];

  doc.autoTable({
    startY: finalY + 20,
    head: expenseHead,
    body: expensesBody.length > 0 ? expensesBody : [['-', 'No expenses recorded', '-']],
    theme: 'striped',
    headStyles: { fillColor: [231, 76, 60] },
    margin: { left: 14 }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(189, 195, 199);
    doc.text(`Generated by RestauTrack on ${new Date().toLocaleString()}`, 14, doc.internal.pageSize.height - 10);
  }

  // Save the PDF
  const filename = `Report_${hotelName === 'ALL' ? 'Aggregated' : hotelName}_${record.date}.pdf`;
  doc.save(filename);
};
